gh: open compare view for current (non-master) branch

diff --git a/scripts/gh b/scripts/gh
--- a/scripts/gh
+++ b/scripts/gh
@@ -1,13 +1,27 @@
 #!/usr/bin/env bash
 
 usage() {
-  echo "usage: $(basename $0)"
-  echo
-  echo "Open the current Git repository in a browser."
+  echo "
+  usage: $(basename $0) [options]
+
+  Open the current Git repository in a browser.
+
+  options:
+
+    --default-branch <branch-name>
+"
 }
 
+project_slug=$(git ls-remote --get-url | sed 's/^.*:\(.*\)[.]git$/\1/')
+default_branch=master
+current_branch=$(git rev-parse --abbrev-ref HEAD)
 case "$1" in
-  -h|--help) usage;;
-  -*) echo "invalid argument $1" 1>&2;;
-  *) open "https://github.com/$(git ls-remote --get-url | sed 's/^.*:\(.*\)[.]git$/\1/')/commits/$(git rev-parse --abbrev-ref HEAD)";;
+  -h|--help) usage ; exit ;;
+  --default-branch) default_branch="$2" ;;
+  -*) echo "invalid argument $1" >&2 ; exit 1 ;;
 esac
+if [ "$current_branch" = "$default_branch" ] ; then
+  open "https://github.com/$project_slug/commits/$default_branch"
+else
+  open "https://github.com/$project_slug/compare/$default_branch...$current_branch"
+fi
